# Generated by Django 3.2.13 on 2022-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('project_type', models.SmallIntegerField(choices=[(0, 'APP'), (1, 'WEB'), (2, '其他')], verbose_name='项目类型')),
                ('project_version', models.CharField(max_length=200, verbose_name='项目版本')),
            ],
        ),
    ]
